version: 0.4


phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - echo install
      
  pre_build:
    commands:
      - echo pre_build_vpp
  build:
    commands:
      - mvn package
      - echo building
  post_build:
    commands:
      - echo post_building
    
artifacts:
  files:
    - target/vpp-rest-api-h2-aws-deploy-0.0.1-SNAPSHOT.jar